188 review sonarcloud hotspots and resolve all of them
GeospatialResearch/Digital-Twins pull request #189
Opened 2024-07-14 22:42 UTC by LukeParky

DESCRIPTION OF PR:

## Developer Checklist
- [ ] Make code change
- [ ] Update tests
  - [ ] Update / create new tests
  - [ ] Ensure these tests have the expected behaviour
  - [ ] Test locally and ensure tests are passing
- [ ] Update documentation
  - [ ] Readme
  - [ ] Docstrings
  - [ ] Comments
  - [ ] Wiki

## Reviewer Checklist
- [ ] Check new code for code smells
- [ ] Check new tests
  - [ ] Ensure adequate coverage
  - [ ] Check for code smells within tests
- [ ] Check if documentation needs updating
  - [ ] Readme
  - [ ] Docstrings
  - [ ] Comments
  - [ ] Wiki

2024-07-15 03:52 UTC, LukeParky reviewed
Self-review LGTM

2024-07-15 03:52 UTC, LukeParky commented on Dockerfile
>  # Remove unused packages. Keep curl for health checking in docker-compose
```suggestion
# Remove unused packages.
```

2024-07-16 04:38 UTC, LukeParky commented on Dockerfile
>  # Remove unused packages. Keep curl for health checking in docker-compose
We do need curl, do not remove this

2024-07-16 04:58 UTC, LukeParky commented
Note of potential error to resolve:

```python
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/src/dynamic_boundary_conditions/river/river_data_from_niwa.py", line 234, in fetch_rec_data_from_niwa\n    raise RuntimeError("Failed to fetch \'rec_data\'.")\nRuntimeError: Failed to fetch \'rec_data\'.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/venv/lib/python3.11/site-packages/celery/app/trace.py", line 451, in trace_task\n    R = retval = fun(*args, **kwargs)\n                 ^^^^^^^^^^^^^^^^^^^^\n  File "/venv/lib/python3.11/site-packages/celery/app/trace.py", line 734, in __protected_call__\n    return self.run(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/src/tasks.py", line 184, in generate_river_inputs\n    main_river.main(selected_polygon, **parameters)\n  File "/app/src/dynamic_boundary_conditions/river/main_river.py", line 177, in main\n    river_data_to_from_db.store_rec_data_to_db(engine)\n  File "/app/src/dynamic_boundary_conditions/river/river_data_to_from_db.py", line 84, in store_rec_data_to_db\n    rec_data = load_backup_rec_data_from_niwa()\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/src/dynamic_boundary_conditions/river/river_data_to_from_db.py", line 43, in load_backup_rec_data_from_niwa\n    raise FileNotFoundError(f"\'rec_data\' file not found: {rec_data_dir}")\nFileNotFoundError: \'rec_data\' file not found: /stored_data/rec_data\n', 'args': "['POLYGON ((172.71678302522903 -43.400136655560765, 172.71678302522903 -43.370613130921434, 172.65156000179044 -43.370613130921434, 172.65156000179044 -43.400136655560765, 172.71678302522903 -43.400136655560765))']", 'kwargs': '{}', 'description': 'raised unexpected', 'internal': False}
```

2024-07-18 22:33 UTC, LukeParky commented
> Note of potential error to resolve:
> 
> ```python
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/src/dynamic_boundary_conditions/river/river_data_from_niwa.py", line 234, in fetch_rec_data_from_niwa\n    raise RuntimeError("Failed to fetch \'rec_data\'.")\nRuntimeError: Failed to fetch \'rec_data\'.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/venv/lib/python3.11/site-packages/celery/app/trace.py", line 451, in trace_task\n    R = retval = fun(*args, **kwargs)\n                 ^^^^^^^^^^^^^^^^^^^^\n  File "/venv/lib/python3.11/site-packages/celery/app/trace.py", line 734, in __protected_call__\n    return self.run(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/src/tasks.py", line 184, in generate_river_inputs\n    main_river.main(selected_polygon, **parameters)\n  File "/app/src/dynamic_boundary_conditions/river/main_river.py", line 177, in main\n    river_data_to_from_db.store_rec_data_to_db(engine)\n  File "/app/src/dynamic_boundary_conditions/river/river_data_to_from_db.py", line 84, in store_rec_data_to_db\n    rec_data = load_backup_rec_data_from_niwa()\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/src/dynamic_boundary_conditions/river/river_data_to_from_db.py", line 43, in load_backup_rec_data_from_niwa\n    raise FileNotFoundError(f"\'rec_data\' file not found: {rec_data_dir}")\nFileNotFoundError: \'rec_data\' file not found: /stored_data/rec_data\n', 'args': "['POLYGON ((172.71678302522903 -43.400136655560765, 172.71678302522903 -43.370613130921434, 172.65156000179044 -43.370613130921434, 172.65156000179044 -43.400136655560765, 172.71678302522903 -43.400136655560765))']", 'kwargs': '{}', 'description': 'raised unexpected', 'internal': False}
> ``

This will be resolved in #143 so blocked by #143

2024-08-14 02:12 UTC, LukeParky commented on Dockerfile
> +COPY --chmod=555 --from=build /venv /venv
Being more explicit with ownership could be better, Casey mentioned implicit was confusing

```suggestion
COPY --chown=root:root --chmod=555 --from=build /venv /venv
```

2024-08-14 02:18 UTC, caseyli92 requested changes
Looks good. Just a reminder to address the two new SonarCloud issues.

2024-08-14 02:18 UTC, caseyli92 commented on Dockerfile
> +
As we discussed, let's add the `chown` command to be more explicit.
```suggestion
COPY --chown=root:root --chmod=555 --from=build /venv /venv
```

2024-08-14 03:15 UTC, caseyli92 approved these changes
Looking good :)

2024-08-14 03:15 UTC, merged