273 migrate to terriajs
GeospatialResearch/Digital-Twins pull request #281
Opened 2024-11-13 04:11 UTC by LukeParky

DESCRIPTION OF PR:
Migrate to using TerriaJS as the primary front-end.
This requires the use of OGC WebProcessingService (WPS) to run processing tasks.

Another issue #280 is for removing the old front-end

## Developer Checklist
- [X] Make code change
- [ ] Update tests
  - [ ] Update / create new tests
  - [ ] Ensure these tests have the expected behaviour
  - [ ] Test locally and ensure tests are passing
- [X] Update documentation
  - [X] Readme
  - [X] Docstrings
  - [X] Comments
  - [ ] Wiki

## Reviewer Checklist
- [ ] Check new code for code smells
- [ ] Check new tests
  - [ ] Ensure adequate coverage
  - [ ] Check for code smells within tests
- [ ] Check if documentation needs updating
  - [ ] Readme
  - [ ] Docstrings
  - [ ] Comments
  - [ ] Wiki

2024-11-13 04:22 UTC, LukeParky commented on src/pywps.cfg
> +outputurl=http://localhost:5000/outputs/
Update this entire file

2024-11-13 04:22 UTC, LukeParky commented on terriajs/client_config.json
> +    "cesiumIonAccessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI4NDE2NGZmYy01MDRjLTQyOWUtYjdlYS05M2RmNTMyMGQzYzIiLCJpZCI6Nzk4NzUsImlhdCI6MTY0MjQ2MzEzNX0.bajvCxkIy698jp_y72DmHCqwN963H7yHm
Use environment variables here (this key has already been disabled)

2024-11-13 04:22 UTC, LukeParky commented on terriajs/client_config.json
> +    "cesiumIonAccessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI4NDE2NGZmYy01MDRjLTQyOWUtYjdlYS05M2RmNTMyMGQzYzIiLCJpZCI6Nzk4NzUsImlhdCI6MTY0MjQ2MzEzNX0.bajvCxkIy698jp_y72DmHCqwN963H7yHm
Or remove the need for it

2024-11-13 04:22 UTC, LukeParky commented on Dockerfile
Update README with additional instructions for copying gdb file while waiting on approval from data owners

2024-11-13 04:24 UTC, LukeParky commented
@caseyli92 this is essentially ready for a code review but additional documentation is required to enable you to easily test it. (you need the .gdb in the correct folder, will add more documentation around this shortly)

2024-11-18 00:30 UTC, LukeParky commented on src/pollution_model/run_medusa_2.py
Add descriptions for tests

2024-11-18 00:30 UTC, caseyli92 requested changes
Great work! I have a few suggestions and comments below. Also, please remember to add a short description to each of the Medusa unit tests.

2024-11-18 00:30 UTC, caseyli92 commented on environment.yml
> +  - conda-pack==0.7.1
Could you please add a comment for this change?

2024-11-18 00:30 UTC, caseyli92 commented on src/app.py
> +@app.route('/wps', methods=['GET', 'POST'])
The SonarCloud hotspot risk needs to be resolved.

2024-11-18 00:30 UTC, caseyli92 commented on src/digitaltwin/data_to_db.py
> +
```suggestion
        log.info("Adding 'roof_surface_points' to the database.")
        roof_surface_points.to_postgis("roof_surface_points", engine, index=False, if_exists="replace")
        log.info("Successfully added 'roof_surface_points' to the database.")
```

2024-11-18 00:30 UTC, caseyli92 commented on src/digitaltwin/data_to_db.py
> +        roof_surface_polygons.to_postgis("roof_surface_polygons", engine, index=False, if_exists="replace")
```suggestion
        log.info("Adding 'roof_surface_polygons' to the database.")
        roof_surface_polygons.to_postgis("roof_surface_polygons", engine, index=False, if_exists="replace")
        log.info("Successfully added 'roof_surface_polygons' to the database.")
```

2024-11-18 00:30 UTC, caseyli92 commented on src/digitaltwin/data_to_db.py
> +    Read roof surface type data, then store them into database.
```suggestion
    """
    Read roof surface type points data then store them into database.
```

2024-11-18 00:30 UTC, caseyli92 commented on src/digitaltwin/data_to_db.py
> +    Read roof surface geometry data then store them into database.
```suggestion
    """
    Read roof surface polygons data then store them into database.
```

2024-11-18 00:30 UTC, caseyli92 commented on src/digitaltwin/data_to_db.py
> +        log.info("roof_surface_points data already exists in the database.")
```suggestion
    if check_table_exists(engine, "roof_surface_points"):
        log.info("'roof_surface_points' data already exists in the database.")
```

2024-11-18 00:30 UTC, caseyli92 commented on src/digitaltwin/data_to_db.py
> +        log.info("roof_surface_polygons data already exists in the database.")
```suggestion
    if check_table_exists(engine, "roof_surface_polygons"):
        log.info("'roof_surface_polygons' data already exists in the database.")
```

2024-11-18 00:30 UTC, caseyli92 commented on src/digitaltwin/data_to_db.py
> +
```suggestion
    """
    Read roof surface type points and polygons from the data file and store them in the database.
```

2024-11-18 00:30 UTC, caseyli92 commented on src/digitaltwin/data_to_db.py
> +def save_roof_surface_type_data_to_db(engine: Engine) -> None:
avoid confusion

```suggestion
def save_roof_surface_data_to_db(engine: Engine) -> None:
```

2024-11-18 00:30 UTC, caseyli92 commented on src/digitaltwin/retrieve_static_boundaries.py
> +    data_to_db.save_roof_surface_type_data_to_db(engine)
```suggestion
    data_to_db.save_roof_surface_data_to_db(engine)
```

2024-11-18 00:53 UTC, LukeParky commented on Dockerfile
> +COPY --chown=root:root --chmod=444 \
The directory is created during copy by this command: https://github.com/GeospatialResearch/Digital-Twins/blob/aa6ba2363fa0e3eedb3e6acbf6ececd67c028e2b/Dockerfile#L52-L55 so the `roof_surfaces_data` directory does not need to be created.

The road surfaces aren't included in this PR so I will leave that for #286.

2024-11-18 00:54 UTC, LukeParky commented on docker-compose-dev.yml
> +
Deferring to #286, see comment https://github.com/GeospatialResearch/Digital-Twins/pull/281/files#r1845696839

2024-11-18 01:49 UTC, caseyli92 approved these changes

2024-11-18 03:17 UTC, merged