36 fix test runner
GeospatialResearch/Digital-Twins pull request #46
Opened 2022-08-22 00:09 UTC by LukeParky

DESCRIPTION OF PR:

## Developer Checklist
- [x] Make code change
- [x] Update tests
  - [x] Update / create new tests
  - [x] Ensure these tests have the expected behaviour
  - [x] Test locally and ensure tests are passing
- [ ] Update documentation
  - [ ] Readme
  - [ ] Docstrings
  - [ ] Comments
  - [ ] Wiki

## Reviewer Checklist
- [ ] Check new code for code smells
- [ ] Check new tests
  - [ ] Ensure adequate coverage
  - [ ] Check for code smells within tests
- [ ] Check if documentation needs updating
  - [ ] Readme
  - [ ] Docstrings
  - [ ] Comments
  - [ ] Wiki

2022-08-22 00:26 UTC, LukeParky commented
Hi @caseyli92, since we were talking about testing earlier today this could be a good opportunity for you to review some test runner configuration.

Check the checklist above and also check the runner actions to make sure the tests are actually running.
This PR will fix the error in all the other PRs for unit tests

2022-08-22 23:09 UTC, caseyli92 commented on README.md
> +Tests exist in the `tests/` folder.
```suggestion
Tests exist in the `tests` folder.
```

2022-08-25 01:25 UTC, caseyli92 commented on .github/workflows/run-tests.yml
> +    name: Run unit tests with pytest
```suggestion
    # Run unit tests with pytest
```

2022-08-25 23:04 UTC, caseyli92 commented on .github/workflows/run-tests.yml
add names to everything

2022-08-25 23:36 UTC, caseyli92 commented on .github/workflows/run-tests.yml
>    sonarcloud:
add names to everything

2022-08-26 01:59 UTC, caseyli92 commented on .github/workflows/run-tests.yml
> +          mamba-version: "*"
as discussed, let's try running without mamba.

2022-08-26 02:02 UTC, caseyli92 requested changes
Looks good, just a couple of changes to be made. Great learning for me as well :) Thanks Luke!

2022-08-26 02:28 UTC, caseyli92 approved these changes
Excellent work :)

2022-08-26 03:09 UTC, LukeParky commented
Closing PR to reopen so that checks are updated, Checks has a problem where linting-flake8 no longer exists but is required.

2022-08-26 03:10 UTC, LukeParky commented
Merging without linting-flake8 since I can not disable the requirement due to github bug.

2022-08-26 03:13 UTC, merged